### PR TITLE
Merge changes in Dev to Master

### PR DESCRIPTION
**Pull request by ajyang99**

### CODE REVIEW

**Comment by hkjayakumar** [comment]
@chrisjluc @bryanc208 We're generally merging from feature branch to master right?
Do we want to keep dev and master in sync?

@ajyang99 Could you hold off on merging this PR

**Comment by chrisjluc** [comment]
@bryanc208 i believe bryan said we can merge dev to master. Can you confirm
bryan?

**Comment by ajyang99** [comment]
@hkjayakumar Sure I will wait

**Comment by chrisjluc** [comment]
@ajyang99 Bryan says you can go ahead and merge this.

**Pull request merged**
